### ISSUE TITLE
Als Nutzer möchte ich durchgehend deutsche Sprache im Accordion-Element

### ISSUE THREAD

**Issue by GiniSt19** [RRZE-Webteam/rrze-elements-blocks#146]
# User Story
Als Nutzer möchte ich durchgehend deutsche Sprache im Accordion-Element

## Grundlegendes Problem
Der Accordiontitel-Platzhaltertext ist auf Englisch "Enter your Title…", der Platzhaltertext darunter wieder auf Deutsch.
Zudem verschwindet der Platzhaltertext nicht und muss immer erst rausgelöscht/ersetzt werden. 

## Möglicher Lösungsvorschlag
Titel übersetzen: "Titel eingeben"

## Weiterer Input oder Inspiration von anderen Lösungen
<img width="1323" alt="Bildschirmfoto 2024-07-11 um 13 08 26" src="https://github.com/RRZE-Webteam/rrze-elements-blocks/assets/174712080/92f15593-3b92-435b-8105-0fdd150c7d4d">

**Comment by lukasniebler** [comment]
In v1.0.7
