### ISSUE TITLE
Hinweisblock "Warnung" hat falsche Schriftgröße

### ISSUE THREAD

**Issue by GiniSt19** [RRZE-Webteam/rrze-elements-blocks#179]
# Beschreibung des Problems
Der Hinweisblock "Warnung" hat eine andere Schriftgröße als die anderen Hinweisblöcke

## Was sollte eigentlich passieren
Schriftgröße anpassen

## Screenshots
<img width="1210" alt="Bildschirmfoto 2024-12-03 um 08 30 51" src="https://github.com/user-attachments/assets/f76bc3f4-93cf-4f17-9539-35badceaa45c">

**Comment by lukasniebler** [comment]
@GiniSt19 Das soll anscheinend so sein. Zumindest gibt es auch im original Elements Plugin ein Styling für eine größere Schrift nur für den Danger Block:

https://github.com/RRZE-Webteam/rrze-elements/blob/9f775c29f4af9d4add6505ef563b9f595841f0f1/assets/css/_alerts.scss#L128

**Comment by lukasniebler** [comment]
In v1.0.13
