### ISSUE TITLE
permission_callback fehlt anscheinend

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-elements-blocks#77]
<b>Notice</b>:  Die Funktion register_rest_route wurde fehlerhaft aufgerufen. Der Definition der REST-API-Route für rrze-elements-blocks/v1/plugin-directory fehlt das erforderliche Argument permission_callback. Für REST-API-Routen, die für öffentlichen Zugriff gedacht sind, benutze __return_true als Berechtigungs-Callback. Weitere Informationen: <a>Debugging in WordPress (engl.)</a>. (Diese Meldung wurde in Version 5.5.0 hinzugefügt.) in <b>/websource/wp-includes/functions.php</b> on line <b>6031</b><br />

**Comment by lukasniebler** [comment]
Tritt der Fehler im Dev oder im Main-Branch auf? Und wann? Bis jetzt konnte ich den Fehler bei mir noch nicht nachstellen.

**Comment by thenickless** [comment]
Notice taucht nicht auf meinem lokalen Server nicht auf.
Ich schließe dieses Issue und erstelle ein neues, falls die Notice mir nochmal begegnet.
